# Generated by Django 4.0.5 on 2022-06-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('comision', models.IntegerField()),
                ('profesor', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateField()),
            ],
        ),
    ]
