# Generated by Django 4.0.5 on 2022-06-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaPruebaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=30)),
                ('fecha_inicio', models.DateField()),
                ('disertante', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='curso',
            name='profesor',
            field=models.CharField(max_length=25),
        ),
    ]
