# Generated by Django 4.0.5 on 2022-06-18 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaPruebaApp', '0002_evento_alter_curso_profesor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='nombre_curso',
            new_name='nombre_evento',
        ),
    ]
