# Generated by Django 4.0.5 on 2022-06-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaPruebaApp', '0003_rename_nombre_curso_evento_nombre_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('estudios', models.CharField(max_length=30)),
                ('acerca_de', models.CharField(max_length=150)),
            ],
        ),
    ]
